### ISSUE TITLE
About clustering

### ISSUE THREAD

**Issue by lhy2749** [FilippoMB/Spectral-Clustering-with-Graph-Neural-Networks-for-Graph-Pooling#2]
Thanks for your great job, how could i use clustering,py on my data?

**Comment by FilippoMB** [comment]
Hi,

the script "clustering.py" shows examples for three types of datasets. Line 42 lets you specify which dataset you want to process.

- **citations networks** ("core", "pubmed", "citeseer"): in this case, your data comes with a graph (A) representing citations between documents, the node features (X) representing the content of each document, and the node labels (Y) representing the class of each document. Note that the classes Y are only used to compute the clustering metrics (homo_score_sc, complete_score_sc, and v_score_sc -- aka NMI) but are not necessary to train the model.

- **cloud**: in this example, the data comes with a graph (A) representing connections between nodes and node features (X) representing 2-D coordinates of each point. There are no node labels in this case and are replaced by a dummy variable Y of all ones: this mean that the 3 clustering metrics computed at the end are meaningless.

- **synth**: in this example, you have the node features (X) and the node labels (Y), but you don't have a graph (A). The latter is built from the data X by using a k-nn graph (line 62), but other options are of course possible.

You can take inspiration from these examples to figure out how to process your data. 
Note that you must write the code to load your data into the A, X, Y variables and insert such a code in a new if-else branch after line 72.

**Comment by lhy2749** [comment]
thank you very much!
